# Python stubs generated by omniidl from deposit.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Deposit"
#
__name__ = "Deposit"
_0_Deposit = omniORB.openModule("Deposit", r"deposit.idl")
_0_Deposit__POA = omniORB.openModule("Deposit__POA", r"deposit.idl")


# interface BankingServer
_0_Deposit._d_BankingServer = (omniORB.tcInternal.tv_objref, "IDL:Deposit/BankingServer:1.0", "BankingServer")
omniORB.typeMapping["IDL:Deposit/BankingServer:1.0"] = _0_Deposit._d_BankingServer
_0_Deposit.BankingServer = omniORB.newEmptyClass()
class BankingServer :
    _NP_RepositoryId = _0_Deposit._d_BankingServer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Deposit.BankingServer = BankingServer
_0_Deposit._tc_BankingServer = omniORB.tcInternal.createTypeCode(_0_Deposit._d_BankingServer)
omniORB.registerType(BankingServer._NP_RepositoryId, _0_Deposit._d_BankingServer, _0_Deposit._tc_BankingServer)

# BankingServer operations and attributes
BankingServer._d_deposit = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), ((omniORB.tcInternal.tv_string,0), ), None)

# BankingServer object reference
class _objref_BankingServer (CORBA.Object):
    _NP_RepositoryId = BankingServer._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def deposit(self, *args):
        return self._obj.invoke("deposit", _0_Deposit.BankingServer._d_deposit, args)

omniORB.registerObjref(BankingServer._NP_RepositoryId, _objref_BankingServer)
_0_Deposit._objref_BankingServer = _objref_BankingServer
del BankingServer, _objref_BankingServer

# BankingServer skeleton
__name__ = "Deposit__POA"
class BankingServer (PortableServer.Servant):
    _NP_RepositoryId = _0_Deposit.BankingServer._NP_RepositoryId


    _omni_op_d = {"deposit": _0_Deposit.BankingServer._d_deposit}

BankingServer._omni_skeleton = BankingServer
_0_Deposit__POA.BankingServer = BankingServer
omniORB.registerSkeleton(BankingServer._NP_RepositoryId, BankingServer)
del BankingServer
__name__ = "Deposit"

#
# End of module "Deposit"
#
__name__ = "deposit_idl"

_exported_modules = ( "Deposit", )

# The end.
