# DO NOT EDIT THIS FILE!
#
# Python module Balance generated by omniidl

import omniORB
omniORB.updateModule("Balance")

# ** 1. Stub files contributing to this module
import balance_idl

# ** 2. Sub-modules

# ** 3. End
