# DO NOT EDIT THIS FILE!
#
# Python module Deposit__POA generated by omniidl

import omniORB
omniORB.updateModule("Deposit__POA")

# ** 1. Stub files contributing to this module
import deposit_idl

# ** 2. Sub-modules

# ** 3. End
