# DO NOT EDIT THIS FILE!
#
# Python module Bank__POA generated by omniidl

import omniORB
omniORB.updateModule("Bank__POA")

# ** 1. Stub files contributing to this module
import bank_idl

# ** 2. Sub-modules

# ** 3. End
