# DO NOT EDIT THIS FILE!
#
# Python module Withdraw__POA generated by omniidl

import omniORB
omniORB.updateModule("Withdraw__POA")

# ** 1. Stub files contributing to this module
import withdraw_idl

# ** 2. Sub-modules

# ** 3. End
